"use client";

import Home from "@/components/Home";
// import type { Metadata } from "next";

// Metadata for the app
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const AppHomePage = () => {
  return (
    <div>
      <Home />
    </div>
  );
};

export default AppHomePage;
